//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int Secuencia { get; set; }
        public bool Pagado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public decimal Monto { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int ProjectId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
